name: Deploy React to VPS

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときにトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウト
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t frontend:latest .

    - name: Save Docker image as tarball
      run: |
        docker save frontend:latest | gzip > frontend.tar.gz

    - name: セットアップNode.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.14'

    - name: React appのビルド
      run: |
        npm install
        npm run build
        ls
  

    - name: サーバーにファイルをアップロード
      uses: appleboy/scp-action@v0.1.3
      with:
        host: 118.27.2.129
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 22
        source: "build/*"
        target: "/root/rest/static/"

    - name: サーバにdockerimageをアップロード
      uses: appleboy/scp-action@v0.1.3
      with:
        host: 118.27.2.129
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 22
        source: "frontend.tar.gz"
        target: "/root/portfolio"
          

    # - name: アップロードしたcss,js,mediaファイルを移動する
    #   uses: appleboy/ssh-action@v0.1.2
    #   with:
    #     host: 118.27.2.129
    #     username: root
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
    #     port: 22
    #     script: |
    #       rm -rf /root/rest/static/css
    #       rm -rf /root/rest/static/js
    #       rm -rf /root/rest/static/media
    #       mv /root/rest/static/build/static/css /root/rest/static/
    #       mv /root/rest/static/build/static/js /root/rest/static/
    #       mv /root/rest/static/build/static/media /root/rest/static/
    #       rm -rf /root/rest/static/build/static/
    #       ls

    - name: サーバでコマンドを実行
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: 118.27.2.129
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 22
        script: |
          cd /root/portfolio
          sudo docker load < frontend.tar.gz
          sudo docker-compose down
          sudo docker-compose up -d

