name: Deploy React to VPS

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときにトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Node.js dependencies and build React app
      run: |
        npm install
        npm run build

    - name: Upload static files to /root/rest/static
      run: |
        scp -r build/static/* user@your-vps-ip:/root/rest/static/

    - name: Upload manifest and other build files to /root/rest/static/build
      run: |
        scp build/*.{json,js,html} user@your-vps-ip:/root/rest/static/build/
